---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nuxtjs
  labels:
    app.kubernetes.io/name: nuxtjs
    app.kubernetes.io/instance: nuxtjs
    app.kubernetes.io/version: "3"
spec:
  replicas: 1
  # strategy:
  #   type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: nuxtjs
      app.kubernetes.io/instance: nuxtjs
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nuxtjs
        app.kubernetes.io/instance: nuxtjs
    spec:
      containers:
        - name: nuxtjs
          envFrom:
            - configMapRef:
                name: nuxtjs
            - secretRef:
                name: nuxtjs
          image: "nuxtjs:3"
          imagePullPolicy: Always
          ports:
            - name: nuxtjs
              containerPort: 3001
              protocol: TCP
          livenessProbe:
            failureThreshold: 12
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: nuxtjs
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 20
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: nuxtjs
            timeoutSeconds: 5
          resources:
            limits:
              memory: 1Gi
              cpu: "1"
            requests:
              memory: 200Mi
              cpu: "0.1"
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
            type: ''
