---
apiVersion: v1
kind: Service
metadata:
  name: nuxtjs
  labels:
    app.kubernetes.io/name: nuxtjs
    app.kubernetes.io/instance: nuxtjs
    app.kubernetes.io/version: "3"
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: nuxtjs
      protocol: TCP
      name: nuxtjs
  selector:
    app.kubernetes.io/name: nuxtjs
    app.kubernetes.io/instance: nuxtjs
