apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
# - secret.yaml
secretGenerator:
  - name: spring
    type: Opaque
configurations:
  - sealed-secret-config.yaml
generatorOptions:
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
    sealedsecrets.bitnami.com/namespace-wide: "true"
