---
apiVersion: v1
kind: Service
metadata:
  name: spring
  labels:
    app.kubernetes.io/name: spring
    app.kubernetes.io/instance: spring
    app.kubernetes.io/version: "2"
spec:
  type: ClusterIP
  ports:
    - port: 8772
      targetPort: spring
      protocol: TCP
      name: spring
  selector:
    app.kubernetes.io/name: spring
    app.kubernetes.io/instance: spring
