---
apiVersion: v1
kind: Service
metadata:
  name: strapi
  labels:
    app.kubernetes.io/name: strapi
    app.kubernetes.io/instance: strapi
    app.kubernetes.io/version: "3"
spec:
  type: ClusterIP
  ports:
    - port: 1337
      targetPort: strapi
      protocol: TCP
      name: strapi
  selector:
    app.kubernetes.io/name: strapi
    app.kubernetes.io/instance: strapi
